	class O_Soldier_base_F;
	class B_Soldier_diver_base_F;
	class TEN_B_C_Base: O_Soldier_base_F
	{
		author="GanX";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"G_IRAN_default"
		};
		faceType="Man_A3";
		side=0;
		faction="TEN_B_C_Faction";
		genericNames="TakistaniMen";
		vehicleClass="Men";
		editorSubcategory="EdSubcat_Personnel";
		portrait="";
		picture="";
		icon="iconMan";
		accuracy=2.3;
		threat[]={0.80000001,0.1,0.1};
		camouflage=1.4;
		minFireTime=7;
		canCarryBackPack=1;
		scope=0;
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		modelSides[]={0,3};
		nakedUniform="U_BasicBody";
		uniformClass="U_O_CombatUniform_ocamo";
		hiddenSelections[]=
		{
			"Camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\OPFOR\Data\clothing_co.paa",
			"\A3\Characters_F\OPFOR\Data\tech_CO.paa"
		};
	};
	class TEN_B_C_Diver_Base: B_Soldier_diver_base_F
	{
		author="GanX";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"G_IRAN_default"
		};
		faceType="Man_A3";
		side=0;
		faction="TEN_B_C_Faction";
		genericNames="TakistaniMen";
		vehicleClass="Men";
		editorSubcategory="EdSubcat_Personnel";
		portrait="";
		picture="";
		icon="iconMan";
		accuracy=2.3;
		threat[]={0.80000001,0.1,0.1};
		camouflage=1.4;
		minFireTime=7;
		canCarryBackPack=1;
		scope=0;
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		model="\A3\characters_F\Common\diver_slotable";
		modelSides[]={0,3};
		nakedUniform="U_BasicBody";
		uniformClass="U_B_Wetsuit";
		hiddenSelections[]=
		{
			"Camo1",
			"Camo2",
			"insignia"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Characters_F\Common\Data\diver_suit_nato_co.paa",
			"\A3\Characters_F\Common\Data\diver_equip_nato_co.paa"
		};
	};
	class TEN_B_C_Base_Miguel: O_Soldier_base_F
	{
		author="GanX";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"G_IRAN_default"
		};
		faceType="Man_A3";
		side=0;
		faction="TEN_B_C_Faction";
		genericNames="TakistaniMen";
		vehicleClass="Men";
		editorSubcategory="EdSubcat_Personnel";
		portrait="";
		picture="";
		icon="iconMan";
		accuracy=2.3;
		threat[]={0.80000001,0.1,0.1};
		camouflage=1.4;
		minFireTime=7;
		canCarryBackPack=1;
		scope=0;
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		model="\A3\Characters_F\Civil\c_poloshirtpants.p3d";
		modelSides[]={0};
		nakedUniform="U_BasicBody";
		uniformClass="TEN_U_C_FormalSuit_01_tshirt_gray_F";
	};
	class TEN_B_C_Base_Javier: O_Soldier_base_F
	{
		author="GanX";
		identityTypes[]=
		{
			"LanguagePER_F",
			"Head_NATO",
			"G_IRAN_default"
		};
		faceType="Man_A3";
		side=0;
		faction="TEN_B_C_Faction";
		genericNames="TakistaniMen";
		vehicleClass="Men";
		editorSubcategory="EdSubcat_Personnel";
		portrait="";
		picture="";
		icon="iconMan";
		accuracy=2.3;
		threat[]={0.80000001,0.1,0.1};
		camouflage=1.4;
		minFireTime=7;
		canCarryBackPack=1;
		scope=0;
		armor=2;
		armorStructural=4;
		explosionShielding=0.40000001;
		model="\A3\Characters_F_EPB\Guerrilla\ig_guerrilla4_1.p3d";
		modelSides[]={0,3};
		nakedUniform="U_BasicBody";
		uniformClass="TEN_U_I_G_resistanceLeader_F";
	};
	class TEN_B_C_Rifleman: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Rifleman (Heavy)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Medic: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Medic (Heavy)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=1;
		icon="iconManMedic";
		picture="pictureHeal";
		backpack="TEN_B_C_Backpack_Medic";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Engineer: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Engineer (Heavy)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="true";
		engineer="true";
		attendant=0;
		icon="iconManEngineer";
		picture="pictureRepair";
		backpack="TEN_B_C_Backpack_Engineer";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_MG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Machine Gunner (Heavy)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManMG";
		backpack="TEN_B_C_Backpack_MG";
		weapons[]=
		{
			"TEN_arifle_CTARS_blk_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TEN_arifle_CTARS_blk_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_AT: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Anti-Tank (Heavy)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManAT";
		backpack="TEN_B_C_Backpack_AT";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"launch_RPG7_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"launch_RPG7_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Marksman: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Marksman (Heavy)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManRecon";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"TEN_srifle_DMR_04_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TEN_srifle_DMR_04_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Officer: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Officer (Heavy)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManOfficer";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Officer",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Officer",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_SL: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Squad Leader (Heavy)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManLeader";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_SL",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_SL",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Rifleman_Light: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Rifleman (Light)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Medic_Light: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Medic (Light)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=1;
		icon="iconManMedic";
		picture="pictureHeal";
		backpack="TEN_B_C_Backpack_Medic";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Engineer_Light: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Engineer (Light)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="true";
		engineer="true";
		attendant=0;
		icon="iconManEngineer";
		picture="pictureRepair";
		backpack="TEN_B_C_Backpack_Engineer";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_MG_Light: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Machine Gunner (Light)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManMG";
		backpack="TEN_B_C_Backpack_MG";
		weapons[]=
		{
			"TEN_arifle_CTARS_blk_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TEN_arifle_CTARS_blk_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_AT_Light: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Anti-Tank (Light)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManAT";
		backpack="TEN_B_C_Backpack_AT";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"launch_RPG7_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"launch_RPG7_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Marksman_Light: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Marksman (Light)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManRecon";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"TEN_srifle_DMR_04_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TEN_srifle_DMR_04_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Officer_Light: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Officer (Light)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManOfficer";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Officer",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Officer",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_SL_Light: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Squad Leader (Light)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManLeader";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_SL",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_SL",
			"G_Balaclava_blk",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Rifleman_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Rifleman (Heavy) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Medic_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Medic (Heavy) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=1;
		icon="iconManMedic";
		picture="pictureHeal";
		backpack="TEN_B_C_Backpack_Medic";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Engineer_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Engineer (Heavy) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="true";
		engineer="true";
		attendant=0;
		icon="iconManEngineer";
		picture="pictureRepair";
		backpack="TEN_B_C_Backpack_Engineer";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_MG_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Machine Gunner (Heavy) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManMG";
		backpack="TEN_B_C_Backpack_MG";
		weapons[]=
		{
			"TEN_arifle_CTARS_blk_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TEN_arifle_CTARS_blk_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_AT_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Anti-Tank (Heavy) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManAT";
		backpack="TEN_B_C_Backpack_AT";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"launch_RPG7_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"launch_RPG7_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Marksman_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Marksman (Heavy) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManRecon";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"TEN_srifle_DMR_04_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TEN_srifle_DMR_04_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Officer_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Officer (Heavy) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManOfficer";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Officer",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Officer",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_SL_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Squad Leader (Heavy) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManLeader";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_SL",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_SL",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Rifleman_Light_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Rifleman (Light) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Medic_Light_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Medic (Light) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=1;
		icon="iconManMedic";
		picture="pictureHeal";
		backpack="TEN_B_C_Backpack_Medic";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Engineer_Light_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Engineer (Light) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="true";
		engineer="true";
		attendant=0;
		icon="iconManEngineer";
		picture="pictureRepair";
		backpack="TEN_B_C_Backpack_Engineer";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_MG_Light_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Machine Gunner (Light) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManMG";
		backpack="TEN_B_C_Backpack_MG";
		weapons[]=
		{
			"TEN_arifle_CTARS_blk_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TEN_arifle_CTARS_blk_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"100Rnd_580x42_Mag_F",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_AT_Light_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Anti-Tank (Light) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManAT";
		backpack="TEN_B_C_Backpack_AT";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"launch_RPG7_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"launch_RPG7_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Marksman_Light_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Marksman (Light) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManRecon";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"TEN_srifle_DMR_04_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"TEN_srifle_DMR_04_F",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"10Rnd_127x54_Mag",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_SL_Light_NVG: TEN_B_C_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Squad Leader (Light) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\OPFOR\o_soldier_01.p3d";
		uniformClass="U_O_R_Gorka_01_black_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManLeader";
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_SL",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_SL",
			"G_Balaclava_blk",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Diver_Light_NVG: TEN_B_C_Diver_Base
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"LanguageENG_F",
			"Head_NATO",
			"G_NATO_default"
		};
		displayName="GX - Diver (Light) (NVG)";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_F\Common\diver_slotable";
		uniformClass="U_B_Wetsuit";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		backpack="TEN_B_C_Backpack";
		weapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_black",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_B_Diving",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"DSF_Wagner_platecarrier_black",
			"TEN_B_M_Extreme",
			"G_B_Diving",
			"O_NVGoggles_grn_F",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Miguel_Blanco: TEN_B_C_Base_Miguel
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"TEN_B_C_Face_Miguel_Blanco"
		};
		displayName="Miguel Blanco";
		vehicleClass="MenStory";
		editorSubcategory="EdSubcat_Personnel_Story";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\characters_f_aow\Uniforms\FormalSuit_01_tshirt_F.p3d";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\Characters_F_AoW\Uniforms\data\FormalSuit_01_tshirt_Gray_CO.paa"
		};
		uniformClass="TEN_U_C_FormalSuit_01_tshirt_gray_F";
		canDeactivateMines="false";
		engineer="false";
		attendant=0;
		icon="iconManLeader";
		backpack="";
		weapons[]=
		{
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]={};
		respawnMagazines[]={};
		linkedItems[]=
		{
			"G_Aviator",
			"H_Hat_checker",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"G_Aviator",
			"H_Hat_checker",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class TEN_B_C_Javier_Blanco: TEN_B_C_Base_Javier
	{
		author="GanX";
		scope=2;
		scopeCurator=2;
		scopeArsenal=2;
		identityTypes[]=
		{
			"TEN_B_C_Face_Javier_Blanco"
		};
		displayName="Javier Blanco";
		vehicleClass="MenStory";
		editorSubcategory="EdSubcat_Personnel_Story";
		cost=200000;
		camouflage=1.5;
		sensitivity=2.5;
		threat[]={1,1,0.80000001};
		model="\A3\Characters_F_EPB\Guerrilla\ig_guerrilla4_1.p3d";
		hiddenSelections[]=
		{
			"camo1"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\characters_f_epb\Guerrilla\data\ig_guerrilla4_1_co.paa"
		};
		uniformClass="TEN_U_I_G_resistanceLeader_F";
		canDeactivateMines="true";
		engineer="true";
		attendant=0;
		icon="iconManLeader";
		backpack="B_AssaultPack_blk";
		weapons[]=
		{
			"SMG_03_camo",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		respawnWeapons[]=
		{
			"SMG_03_camo",
			"hgun_Pistol_heavy_02_F",
			"Rangefinder",
			"Throw",
			"Put"
		};
		Items[]={};
		RespawnItems[]={};
		magazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		respawnMagazines[]=
		{
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"50Rnd_570x28_SMG_03",
			"6Rnd_45ACP_Cylinder",
			"6Rnd_45ACP_Cylinder"
		};
		linkedItems[]=
		{
			"TEN_B_M_Up",
			"V_Rangemaster_belt",
			"G_Sport_Blackred",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
		respawnLinkedItems[]=
		{
			"TEN_B_M_Up",
			"V_Rangemaster_belt",
			"G_Sport_Blackred",
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"ItemGPS"
		};
	};
	class B_CivilianBackpack_01_Everyday_Black_F;
	class TEN_B_C_Backpack: B_CivilianBackpack_01_Everyday_Black_F
	{
		class TransportMagazines
		{
			class TEN_SmokeShell
			{
				magazine="SmokeShell";
				count=5;
			};
			class TEN_SmokeShellRed
			{
				magazine="SmokeShellRed";
				count=5;
			};
			class TEN_HandGrenade
			{
				magazine="HandGrenade";
				count=2;
			};
			class TEN_Chemlight_red
			{
				magazine="Chemlight_red";
				count=4;
			};
		};
		class TransportItems
		{
			class TEN_FirstAidKit
			{
				name="FirstAidKit";
				count=5;
			};
		};
	};
	class TEN_B_C_Backpack_Medic: B_CivilianBackpack_01_Everyday_Black_F
	{
		class TransportMagazines
		{
			class TEN_SmokeShell
			{
				magazine="SmokeShell";
				count=5;
			};
			class TEN_SmokeShellRed
			{
				magazine="SmokeShellRed";
				count=5;
			};
			class TEN_HandGrenade
			{
				magazine="HandGrenade";
				count=2;
			};
			class TEN_Chemlight_red
			{
				magazine="Chemlight_red";
				count=4;
			};
		};
		class TransportItems
		{
			class TEN_FirstAidKit
			{
				name="FirstAidKit";
				count=5;
			};
			class TEN_Medikit
			{
				name="Medikit";
				count=1;
			};
		};
	};
	class TEN_B_C_Backpack_Engineer: B_CivilianBackpack_01_Everyday_Black_F
	{
		class TransportMagazines
		{
			class TEN_SmokeShell
			{
				magazine="SmokeShell";
				count=5;
			};
			class TEN_SmokeShellRed
			{
				magazine="SmokeShellRed";
				count=5;
			};
			class TEN_HandGrenade
			{
				magazine="HandGrenade";
				count=2;
			};
			class TEN_Chemlight_red
			{
				magazine="Chemlight_red";
				count=4;
			};
		};
		class TransportItems
		{
			class TEN_FirstAidKit
			{
				name="FirstAidKit";
				count=5;
			};
			class TEN_Toolkit
			{
				name="Toolkit";
				count=1;
			};
			class TEN_MineDetector
			{
				name="MineDetector";
				count=1;
			};
		};
	};
	class TEN_B_C_Backpack_MG: B_CivilianBackpack_01_Everyday_Black_F
	{
		class TransportMagazines
		{
			class TEN_SmokeShell
			{
				magazine="SmokeShell";
				count=5;
			};
			class TEN_SmokeShellRed
			{
				magazine="SmokeShellRed";
				count=5;
			};
			class TEN_HandGrenade
			{
				magazine="HandGrenade";
				count=2;
			};
			class TEN_Chemlight_red
			{
				magazine="Chemlight_red";
				count=4;
			};
			class TEN_100Rnd_580x42_Mag_F
			{
				magazine="100Rnd_580x42_Mag_F";
				count=6;
			};
		};
		class TransportItems
		{
			class TEN_FirstAidKit
			{
				name="FirstAidKit";
				count=5;
			};
		};
	};
	class TEN_B_C_Backpack_AT: B_CivilianBackpack_01_Everyday_Black_F
	{
		class TransportMagazines
		{
			class TEN_SmokeShell
			{
				magazine="SmokeShell";
				count=5;
			};
			class TEN_SmokeShellRed
			{
				magazine="SmokeShellRed";
				count=5;
			};
			class TEN_HandGrenade
			{
				magazine="HandGrenade";
				count=2;
			};
			class TEN_Chemlight_red
			{
				magazine="Chemlight_red";
				count=4;
			};
			class TEN_RPG7_F
			{
				magazine="RPG7_F";
				count=4;
			};
		};
		class TransportItems
		{
			class TEN_FirstAidKit
			{
				name="FirstAidKit";
				count=5;
			};
		};
	};
	class LandVehicle;
	class Car: LandVehicle
	{
		class HitPoints;
		class NewTurret;
	};
	class Car_F: Car
	{
		class Turrets
		{
			class MainTurret: NewTurret
			{
				class ViewOptics;
				class ViewGunner;
			};
		};
		class HitPoints
		{
			class HitLFWheel;
			class HitLF2Wheel;
			class HitRFWheel;
			class HitRF2Wheel;
			class HitBody;
			class HitFuel;
			class HitEngine;
			class HitGlass1
			{
			};
			class HitGlass2;
		};
		class EventHandlers;
		class AnimationSources;
	};
	class Offroad_01_base_F;
	class Offroad_01_AT_base_F;
	class Offroad_01_military_base_F;
	class I_G_Offroad_01_AT_F;
	class B_G_Offroad_01_armed_F;
	class B_G_Offroad_01_AT_F;
	class C_Offroad_01_comms_F;
	class C_Offroad_01_covered_F;
	class Quadbike_01_base_F;
	class I_G_Quadbike_01_F;
	class B_G_Quadbike_01_F;
	class Truck_F;
	class Van_02_base_F;
	class Van_02_transport_base_F;
	class B_G_Van_02_transport_F;
	class Rubber_duck_base_F;
	class I_G_Boat_Transport_01_F;
	class B_G_Boat_Transport_01_F;
	class Air;
	class Plane: Air
	{
		class HitPoints;
	};
	class Plane_Base_F: Plane
	{
		class AnimationSources;
		class HitPoints: HitPoints
		{
			class HitHull;
		};
		class Turrets
		{
			class CopilotTurret;
		};
		class ViewPilot;
		class Components;
	};
	class Plane_Civil_01_base_F;
	class C_Plane_Civil_01_racing_F;
	class Heli_Light_01_base_F;
	class Heli_Light_01_unarmed_base_F;
	class C_Heli_Light_01_civil_F;
	class O_Heli_Light_02_dynamicLoadout_F;
	class B_G_HMG_02_high_F;
	class B_G_HMG_02_F;
	class B_Mortar_01_F;
	class B_Boat_Transport_01_F;
	class I_C_Boat_Transport_02_F;
	class C_Boat_Civil_01_F;
	class O_UAV_01_F;
	class C_UAV_06_F;
	class B_SDV_01_F;
	class TEN_B_C_Offroad_Comms: C_Offroad_01_comms_F
	{
		displayName="GX - Offroad Comms";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman";
		side=0;
		faction="TEN_B_C_Faction";
	};
	class TEN_B_C_Offroad_Covered: C_Offroad_01_covered_F
	{
		displayName="GX - Offroad Covered";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman";
		side=0;
		faction="TEN_B_C_Faction";
	};
	class TEN_B_C_Offroad_MG: B_G_Offroad_01_armed_F
	{
		displayName="GX - Offroad Technical (MG)";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman";
		typicalCargo[]=
		{
			"TEN_B_C_Rifleman"
		};
		side=0;
		faction="TEN_B_C_Faction";
		textureList[]=
		{
			"Black"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_blk_CO.paa",
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_blk_CO.paa",
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_cover_blk_co.paa"
		};
		class AnimationSources
		{
			class Hide_Shield
			{
				displayName="$STR_A3_C_CfgVehicles_Offroad_01_armed_base_F_AnimationSources_Hide_Shield0";
				useSource=1;
				source="user";
				animPeriod=0.0099999998;
				initPhase=0;
			};
			class Hide_Rail
			{
				displayName="$STR_A3_C_CfgVehicles_HMG_02_base_F_AnimationSources_Hide_Rail0";
				useSource=1;
				source="user";
				animPeriod=0.0099999998;
				initPhase=0;
			};
		};
	};
	class TEN_B_C_Offroad_MG_NVG: B_G_Offroad_01_armed_F
	{
		displayName="GX - Offroad Technical (MG) (NVG)";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_NVG";
		typicalCargo[]=
		{
			"TEN_B_C_Rifleman_NVG"
		};
		side=0;
		faction="TEN_B_C_Faction";
		textureList[]=
		{
			"Black"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_blk_CO.paa",
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_blk_CO.paa",
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_cover_blk_co.paa"
		};
		class AnimationSources
		{
			class Hide_Shield
			{
				displayName="$STR_A3_C_CfgVehicles_Offroad_01_armed_base_F_AnimationSources_Hide_Shield0";
				useSource=1;
				source="user";
				animPeriod=0.0099999998;
				initPhase=0;
			};
			class Hide_Rail
			{
				displayName="$STR_A3_C_CfgVehicles_HMG_02_base_F_AnimationSources_Hide_Rail0";
				useSource=1;
				source="user";
				animPeriod=0.0099999998;
				initPhase=0;
			};
		};
	};
	class TEN_B_C_Offroad_AT: B_G_Offroad_01_AT_F
	{
		displayName="GX - Offroad Technical (AT)";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman";
		typicalCargo[]=
		{
			"TEN_B_C_Rifleman"
		};
		side=0;
		faction="TEN_B_C_Faction";
		textureList[]=
		{
			"Black"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_blk_CO.paa",
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_blk_CO.paa",
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_cover_blk_co.paa"
		};
	};
	class TEN_B_C_Offroad_AT_NVG: B_G_Offroad_01_AT_F
	{
		displayName="GX - Offroad Technical (AT) (NVG)";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_NVG";
		typicalCargo[]=
		{
			"TEN_B_C_Rifleman_NVG"
		};
		side=0;
		faction="TEN_B_C_Faction";
		textureList[]=
		{
			"Black"
		};
		hiddenSelectionsTextures[]=
		{
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_blk_CO.paa",
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_ext_blk_CO.paa",
			"\a3\Soft_F_Enoch\Offroad_01\Data\offroad_01_cover_blk_co.paa"
		};
	};
	class TEN_B_C_Van: B_G_Van_02_transport_F
	{
		displayName="GX - Van";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman";
		side=0;
		faction="TEN_B_C_Faction";
		textureList[]=
		{
			"Black",
			1
		};
	};
	class TEN_B_C_Quad: B_G_Quadbike_01_F
	{
		displayName="GX - Quad";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman";
		typicalCargo[]=
		{
			"TEN_B_C_Marksman"
		};
		side=0;
		faction="TEN_B_C_Faction";
		hiddenSelections[]=
		{
			"camo1",
			"camo2"
		};
		hiddenSelectionsTextures[]=
		{
			"\A3\Soft_F_Beta\Quadbike_01\Data\Quadbike_01_CIV_BLACK_CO.paa",
			"\A3\Soft_F_Beta\Quadbike_01\Data\Quadbike_01_wheel_CIVBLACK_CO.paa"
		};
		class TextureSources
		{
			class TEN_B_C_Quad_Tex01
			{
				textures[]=
				{
					"\A3\Soft_F_Beta\Quadbike_01\Data\Quadbike_01_CIV_BLACK_CO.paa",
					"\A3\Soft_F_Beta\Quadbike_01\Data\Quadbike_01_wheel_CIVBLACK_CO.paa"
				};
				factions[]=
				{
					"OPF_F"
				};
			};
		};
	};
	class TEN_B_C_Helicopter: C_Heli_Light_01_civil_F
	{
		displayName="GX - M-900";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_Light_NVG";
		typicalCargo[]=
		{
			"TEN_B_C_Rifleman_Light_NVG"
		};
		side=0;
		faction="TEN_B_C_Faction";
		textureList[]=
		{
			"Digital",
			1
		};
	};
	class TEN_B_C_Helicopter_02: O_Heli_Light_02_dynamicLoadout_F
	{
		displayName="GX - PO-30 Orca (Armed)";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_Light_NVG";
		typicalCargo[]=
		{
			"TEN_B_C_Rifleman_Light_NVG"
		};
		side=0;
		faction="TEN_B_C_Faction";
		hiddenSelectionsTextures[]=
		{
			"\A3\Air_F\Heli_Light_02\Data\Heli_Light_02_ext_CO.paa"
		};
		class Components
		{
			class TransportPylonsComponent
			{
				uiPicture="\A3\Air_F\Heli_Light_02\Data\UI\Heli_Light_02_3DEN_CA.paa";
				class Pylons
				{
					class PylonLeft1
					{
						attachment="PylonWeapon_300Rnd_20mm_shells";
						priority=5;
						hardpoints[]=
						{
							"O_SKYFIRE",
							"DAGR",
							"DAR",
							"I_ORCA_RIGHT_PYLON",
							"20MM_TWIN_CANNON",
							"SCALPEL_1RND_EJECTOR",
							"B_ASRRAM_EJECTOR"
						};
						UIposition[]={0.059999999,0.40000001};
					};
					class PylonRight1: PylonLeft1
					{
						attachment="PylonRack_19Rnd_Rocket_Skyfire";
						mirroredMissilePos=1;
						hardpoints[]=
						{
							"O_SKYFIRE",
							"DAGR",
							"DAR",
							"20MM_TWIN_CANNON",
							"SCALPEL_1RND_EJECTOR",
							"B_ASRRAM_EJECTOR"
						};
						UIposition[]={0.58999997,0.40000001};
					};
				};
				class Presets
				{
					class Empty
					{
						displayName="$STR_empty";
						attachment[]={};
					};
					class Default
					{
						displayName="$STR_vehicle_default";
						attachment[]=
						{
							"PylonWeapon_2000Rnd_65x39_belt",
							"PylonRack_12Rnd_PG_missiles"
						};
					};
					class AT
					{
						displayName="$STR_A3_cfgmagazines_titan_at_dns";
						attachment[]=
						{
							"PylonRack_12Rnd_PG_missiles",
							"PylonRack_12Rnd_PG_missiles"
						};
					};
					class CAS
					{
						displayName="$STR_A3_CAS_PRESET_DISPLAYNAME";
						attachment[]=
						{
							"PylonRack_12Rnd_missiles",
							"PylonRack_12Rnd_missiles"
						};
					};
				};
			};
		};
	};
	class TEN_B_C_Plane: C_Plane_Civil_01_racing_F
	{
		displayName="GX - Caesar BTT (Smuggling)";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_Light_NVG";
		typicalCargo[]=
		{
			"TEN_B_C_Rifleman_Light_NVG"
		};
		side=0;
		faction="TEN_B_C_Faction";
		hiddenSelections[]=
		{
			"camo1",
			"camo2",
			"camo3",
			"camo4"
		};
		hiddenSelectionsTextures[]=
		{
			"TEN_BLANCO_CARTEL\Textures\Planes\TEN_B_C_Plane_01_CO.paa",
			"TEN_BLANCO_CARTEL\Textures\Planes\TEN_B_C_Plane_02_CO.paa",
			"A3\Air_F_Exp\Plane_Civil_01\Data\btt_int_01_tan_co.paa",
			"A3\Air_F_Exp\Plane_Civil_01\Data\btt_int_02_tan_co.paa"
		};
		class TextureSources
		{
			class TEN_B_C_Plane_Tex01
			{
				textures[]=
				{
					"TEN_BLANCO_CARTEL\Textures\Planes\TEN_B_C_Plane_01_CO.paa",
					"TEN_BLANCO_CARTEL\Textures\Planes\TEN_B_C_Plane_02_CO.paa",
					"A3\Air_F_Exp\Plane_Civil_01\Data\btt_int_01_tan_co.paa",
					"A3\Air_F_Exp\Plane_Civil_01\Data\btt_int_02_tan_co.paa"
				};
				factions[]=
				{
					"OPF_F"
				};
			};
		};
	};
	class TEN_B_C_Static_M2_Raised: B_G_HMG_02_high_F
	{
		displayName="GX - M2 HMG .50 (Raised)";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_Light_NVG";
		side=0;
		faction="TEN_B_C_Faction";
		class AnimationSources
		{
			class Hide_Rail
			{
				displayName="$STR_A3_C_CfgVehicles_HMG_02_base_F_AnimationSources_Hide_Rail0";
				useSource=1;
				source="user";
				animPeriod=0.0099999998;
				initPhase=0;
			};
		};
	};
	class TEN_B_C_Static_M2: B_G_HMG_02_F
	{
		displayName="GX - M2 HMG .50";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_Light_NVG";
		side=0;
		faction="TEN_B_C_Faction";
		class AnimationSources
		{
			class Hide_Rail
			{
				displayName="$STR_A3_C_CfgVehicles_HMG_02_base_F_AnimationSources_Hide_Rail0";
				useSource=1;
				source="user";
				animPeriod=0.0099999998;
				initPhase=0;
			};
		};
	};
	class TEN_B_C_Static_Mortar: B_Mortar_01_F
	{
		displayName="GX - Mortar";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_Light_NVG";
		side=0;
		faction="TEN_B_C_Faction";
	};
	class TEN_B_C_Boat_01: B_Boat_Transport_01_F
	{
		displayName="GX - Assault Boat";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_Light_NVG";
		typicalCargo[]={};
		side=0;
		faction="TEN_B_C_Faction";
	};
	class TEN_B_C_Boat_02: I_C_Boat_Transport_02_F
	{
		displayName="GX - RHIB";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_Light_NVG";
		typicalCargo[]={};
		side=0;
		faction="TEN_B_C_Faction";
	};
	class TEN_B_C_Boat_03: C_Boat_Civil_01_F
	{
		displayName="GX - Speed Boat";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Rifleman_Light_NVG";
		typicalCargo[]={};
		side=0;
		faction="TEN_B_C_Faction";
	};
	class TEN_B_C_Drone_01: O_UAV_01_F
	{
		displayName="GX - Recon Drone";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="O_UAV_AI";
		typicalCargo[]={};
		side=0;
		faction="TEN_B_C_Faction";
	};
	class TEN_B_C_Drone_02: C_UAV_06_F
	{
		displayName="GX - Utility Drone";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="O_UAV_AI";
		typicalCargo[]={};
		side=0;
		faction="TEN_B_C_Faction";
	};
	class TEN_B_C_Sub_01: B_SDV_01_F
	{
		displayName="GX - SDV";
		author="GanX";
		scope=2;
		scopeCurator=2;
		crew="TEN_B_C_Diver_Light_NVG";
		typicalCargo[]={};
		side=0;
		faction="TEN_B_C_Faction";
	};